version: "3.9"
services:
  variational_gaussian_process:
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility]
    image: variational_gaussian_process:2.6.0
    entrypoint: python src/main/python/app.py

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: variational_gaussian_process:2.6.0
    entrypoint: pyb -v

  variational_gaussian_process_cpu:
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: "8gb"
    ulimits:
      memlock: -1
      stack: 67108864
    image: variational_gaussian_process:2.6.0
    entrypoint: python src/main/python/app.py
