version: "3.9"
services:
  variational_gaussian_process:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: variational_gaussian_process:2.6.0
    entrypoint: python src/main/python/app.py

  variational_gaussian_process_cpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: variational_gaussian_process:2.6.0
    entrypoint: python src/main/python/app.py
